name: schematic-schema-convert

on:
  push:
    branches:    
      - '**'      # matches every branch
      - '!main'   # excludes main
    paths:
      - 'nf_research_tools.rdb.model.csv'

  workflow_dispatch:

env:
  schema_filename: nf_research_tools.rdb.model.csv
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pip python3.10-venv libcurl4-openssl-dev
      
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository
 
      - name: Install schematic and convert schema #temporarily revert to this to use edge version of schematic
        shell: bash
        run: |
          # use 'poetry' to install schematic from the develop branch 
          pip3 install poetry
          # clone patched branch until develop is stable
          git clone https://github.com/Sage-Bionetworks/schematic.git
          cd schematic
          git checkout 74d3b98f97eb14f70e9f6ad3a02005812b237329
          poetry build
          pip3 install dist/schematicpy-1.0.0-py3-none-any.whl
          cd ..
          schematic schema convert $schema_filename -o nf-research-tools.jsonld

          
      - name: Commit files
        run: |
          git config --local user.email "nf-osi@sagebionetworks.org"
          git config --local user.name "nf-osi[bot]"
          git commit -m "Add changes" -a
    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: ${{ github.ref }}
